// Code generated by MockGen. DO NOT EDIT.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "project-budget-service/internal/domain"
)

type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
}

type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

func (m *MockProjectRepository) CreateProject(ctx context.Context, in domain.CreateProject) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, in)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) CreateProject(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectRepository)(nil).CreateProject), ctx, in)
}

func (m *MockProjectRepository) ListProjects(ctx context.Context, userID domain.UserID) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, userID)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) ListProjects(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectRepository)(nil).ListProjects), ctx, userID)
}

func (m *MockProjectRepository) GetProject(ctx context.Context, projectID domain.ProjectID) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) GetProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectRepository)(nil).GetProject), ctx, projectID)
}

func (m *MockProjectRepository) UpdateProject(ctx context.Context, projectID domain.ProjectID, in domain.UpdateProject) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, projectID, in)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) UpdateProject(ctx, projectID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectRepository)(nil).UpdateProject), ctx, projectID, in)
}

func (m *MockProjectRepository) DeleteProject(ctx context.Context, projectID domain.ProjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProjectRepositoryMockRecorder) DeleteProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectRepository)(nil).DeleteProject), ctx, projectID)
}

func (m *MockProjectRepository) CreateStage(ctx context.Context, in domain.CreateStage) (*domain.Stage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStage", ctx, in)
	ret0, _ := ret[0].(*domain.Stage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) CreateStage(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStage", reflect.TypeOf((*MockProjectRepository)(nil).CreateStage), ctx, in)
}

func (m *MockProjectRepository) UpdateStage(ctx context.Context, in domain.UpdateStage) (*domain.Stage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStage", ctx, in)
	ret0, _ := ret[0].(*domain.Stage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) UpdateStage(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStage", reflect.TypeOf((*MockProjectRepository)(nil).UpdateStage), ctx, in)
}

func (m *MockProjectRepository) DeleteStage(ctx context.Context, projectID domain.ProjectID, stageID domain.StageID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStage", ctx, projectID, stageID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProjectRepositoryMockRecorder) DeleteStage(ctx, projectID, stageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStage", reflect.TypeOf((*MockProjectRepository)(nil).DeleteStage), ctx, projectID, stageID)
}

func (m *MockProjectRepository) ListResources(ctx context.Context) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", ctx)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) ListResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockProjectRepository)(nil).ListResources), ctx)
}

func (m *MockProjectRepository) AddProjectResource(ctx context.Context, in domain.AddProjectResource) (*domain.ProjectResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProjectResource", ctx, in)
	ret0, _ := ret[0].(*domain.ProjectResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) AddProjectResource(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProjectResource", reflect.TypeOf((*MockProjectRepository)(nil).AddProjectResource), ctx, in)
}

func (m *MockProjectRepository) ListProjectResources(ctx context.Context, projectID domain.ProjectID) ([]domain.ProjectResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectResources", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) ListProjectResources(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectResources", reflect.TypeOf((*MockProjectRepository)(nil).ListProjectResources), ctx, projectID)
}

func (m *MockProjectRepository) UpdateProjectResourceWorkload(ctx context.Context, projectID domain.ProjectID, resourceID domain.ResourceID, workload float64) (*domain.ProjectResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectResourceWorkload", ctx, projectID, resourceID, workload)
	ret0, _ := ret[0].(*domain.ProjectResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) UpdateProjectResourceWorkload(ctx, projectID, resourceID, workload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectResourceWorkload", reflect.TypeOf((*MockProjectRepository)(nil).UpdateProjectResourceWorkload), ctx, projectID, resourceID, workload)
}

func (m *MockProjectRepository) DeleteProjectResource(ctx context.Context, projectID domain.ProjectID, resourceID domain.ResourceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectResource", ctx, projectID, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProjectRepositoryMockRecorder) DeleteProjectResource(ctx, projectID, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectResource", reflect.TypeOf((*MockProjectRepository)(nil).DeleteProjectResource), ctx, projectID, resourceID)
}

func (m *MockProjectRepository) GrantAccess(ctx context.Context, projectID domain.ProjectID, access domain.ProjectAccess) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAccess", ctx, projectID, access)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProjectRepositoryMockRecorder) GrantAccess(ctx, projectID, access any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockProjectRepository)(nil).GrantAccess), ctx, projectID, access)
}

func (m *MockProjectRepository) RevokeAccess(ctx context.Context, projectID domain.ProjectID, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccess", ctx, projectID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProjectRepositoryMockRecorder) RevokeAccess(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockProjectRepository)(nil).RevokeAccess), ctx, projectID, userID)
}

func (m *MockProjectRepository) GetAccessRole(ctx context.Context, projectID domain.ProjectID, userID domain.UserID) (domain.AccessRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessRole", ctx, projectID, userID)
	ret0, _ := ret[0].(domain.AccessRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProjectRepositoryMockRecorder) GetAccessRole(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessRole", reflect.TypeOf((*MockProjectRepository)(nil).GetAccessRole), ctx, projectID, userID)
}

type MockBudgetPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetPublisherMockRecorder
}

type MockBudgetPublisherMockRecorder struct {
	mock *MockBudgetPublisher
}

func NewMockBudgetPublisher(ctrl *gomock.Controller) *MockBudgetPublisher {
	mock := &MockBudgetPublisher{ctrl: ctrl}
	mock.recorder = &MockBudgetPublisherMockRecorder{mock}
	return mock
}

func (m *MockBudgetPublisher) EXPECT() *MockBudgetPublisherMockRecorder {
	return m.recorder
}

func (m *MockBudgetPublisher) Publish(ctx context.Context, projectID domain.ProjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBudgetPublisherMockRecorder) Publish(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBudgetPublisher)(nil).Publish), ctx, projectID)
}
